### ISSUE TITLE
Publish articles about the Engineering Process after deployment

### ISSUE THREAD

**Issue by FanJups** [osscameroon/js-generator#124]
We should publish on our Wiki, osscameroon blog , DZone, Medium, LinkedIn, Twitter,...

**Comment by PILOTEZEBS** [comment]
je comprend pas cette issue. je vois qui y a déjà un wiki a propos de JS generator. mais que voulez vous dire par Publier???
publier sur le site? ou publier sur le Readme?

**Comment by FanJups** [comment]
En plus du Wiki, on fera d'autres articles sur d'autres plateformes.

**Comment by PILOTEZEBS** [comment]
<c:out value:" ````ok ok je vois! ```` "/>;
<img src="https://media.brawltime.ninja/brawlers/tick/pins/Pin-ThanksAnim.gif?size=160"/>
@PILOTEZEBS
