### ISSUE TITLE
add the compiled file (.jar) in  the repository

### ISSUE THREAD

**Issue by ngdream** [osscameroon/js-generator#144]

**Comment by FanJups** [comment]
Hi bro, Why do we need to add compiled jar ? Do you have a difficulty ? The jar is generated by the maven build locally and here. There is Continuous Integration process responsible for that: https://github.com/osscameroon/js-generator/blob/main/.github/workflows/maven.yml

**Comment by FanJups** [comment]
Hi bro, do you still have issues ?
