### ISSUE TITLE
Using Spring Boot Custom Banners

### ISSUE THREAD

**Issue by FanJups** [osscameroon/js-generator#252]
https://www.baeldung.com/spring-boot-disable-banner

https://www.baeldung.com/spring-boot-custom-banners

**Comment by shrutikumar15** [comment]
Hi, I would like to be assigned this issue!

**Comment by FanJups** [comment]
> Hi, I would like to be assigned this issue!

Hello, thanks for wanting to contribute but we already have a PR #254   that we will review. Next time, don't wait for an issue to be assigned to you, just start if no one is working on that issue 😊. Well, we will see if we have new issues for new comers.
