### ISSUE TITLE
Read Html Input Files and Generate Js Output Files in  resources folder

### ISSUE THREAD

**Issue by FanJups** [osscameroon/js-generator#8]
@elroykanye , I already created 2 folders htmlFilesInput and jsFilesOutput in src/main/resources, we will write code in order to read "sample.html" from htmlFilesInput folder and generate js file in jsFilesOutput folder. It's not a good idea to have these files at the root.

**Comment by elroykanye** [comment]
🤔 alright, I get it 👌🏾
